//admin actions
export const AdminActionTypes = {
  ADD_ADMIN: "ADD_ADMIN",
  ADD_FACULTY: "ADD_FACULTY",
  ADD_STUDENT: "ADD_STUDENT",
  ADD_SUBJECT: "ADD_SUBJECT",
  GET_ALL_FACULTIES: "GET_ALL_FACULTIES",
  GET_ALL_STUDENTS: "GET_ALL_STUDENTS",
  GET_ALL_SUBJECTS: "GET_ALL_SUBJECTS",
};
